resources:
  - name:       curatedocker
    type:       IncomingWebhook
    configuration:
      webhookName: curate_docker

pipelines:
  - name: CurateDocker
    steps:
    - name: ExampleStep
      type: Bash
      configuration:
        integrations:
          - name: artifactory
        inputResources:
          - name: curatedocker
      execution:
          onExecute:
            - docker login -u `echo "${int_artifactory_user}"` -p `echo "${int_artifactory_apikey}"` `echo "${int_artifactory_url}" | sed -E 's/.*\/\/([^\/]+).*/\1/'`
            - echo "$res_curatedocker_payload" | jq '.' > payload.json
            - echo `read_json payload.json "image"`
            - dockerpulloutput="$(docker pull `read_json payload.json 'image'` 2>&1 || true)"
            - xrayblocked=$(echo "$dockerpulloutput" | grep -c "blocking policy configured in Xray")
            - if [ $xrayblocked -eq 0 ] then echo "success, need to copy to curated"; else echo "blocked by xray"; fi


