resources:
  - name: curatemaven
    type: IncomingWebhook
    configuration:
      webhookName: curate_maven

  - name: mygitrepo
    type: GitRepo
    configuration:
      gitProvider: Github_Sample
      path: shimib/curation_pre
      branches:
        include: main
      buildOn:
        commit: false

pipelines:
  - name: CurateMaven
    steps:
    - name: ExampleStep
      type: Bash
      configuration:
        integrations:
          - name: artifactory
        inputResources:
          - name: curatemaven
          - name: mygitrepo
            trigger: false
        runtime:
          type: image
          image:
           auto:
            language: java
            versions:
              - "17"
      execution:
          onExecute:
            - mvn -version
            - python3 --version
            - ls -lR
            - cp ./dependencyState/resources/mygitrepo/curate_maven.py .
            - python3 curate_maven.py
