resources:
  - name:       curatemaven
    type:       IncomingWebhook
    configuration:
      webhookName: curate_maven

pipelines:
  - name: CurateMaven
    steps:
    - name: ExampleStep
      type: Bash
      configuration:
        integrations:
          - name: artifactory
        inputResources:
          - name: curatemaven
        runtime:
          type: image
          image:
           auto:
            language: java
            versions:
              - "17"
      execution:
          onExecute:
            - mvn -version
            - echo "$res_curatemaven_payload" | jq '.' > payload.json
            - echo `read_json payload.json "pomdata"`
            - pomdata="$(read_json payload.json 'pomdata' | base64 -d)"
            - echo "$pomdata" > pom.xml
            - mvn dependency:list
