resources:
  - name: curatesomething
    type: IncomingWebhook
    configuration:
      webhookName: curate_something

#  - name: mygitrepo
#    type: GitRepo
#    configuration:
#      gitProvider: Github_Sample
#      path: shimib/curation_pre
#      branches:
#        include: main

pipelines:
  - name: CurateBuildSomething
#    configuration:
#      environmentVariables:
#        readOnly:
#          local_repo_name: danielw-docker-local
#          remote_repo_name: shimi-curated
    steps:
      - name: PullBaseDockerImage
        type: Bash
        configuration:
          integrations:
            - name: artifactory
          inputResources:
            - name: curatesomething
        execution:
          onExecute:
            - echo `echo "${int_artifactory_url}" | sed -E 's/.*\/\/([^\/]+).*/\1/'`
            - docker login -u `echo "${int_artifactory_user}"` -p `echo "${int_artifactory_apikey}"` `echo "${int_artifactory_url}" | sed -E 's/.*\/\/([^\/]+).*/\1/'`
