resources:
  - name:       curatedocker
    type:       IncomingWebhook
    configuration:
      webhookName: curate_docker

pipelines:
  - name: CurateDocker
    steps:
    - name: ExampleStep
      type: Bash
      configuration:
        inputResources:
          - name: curatedocker
      execution:
          onExecute:
            - echo "$res_curatedocker_payload" | jq '.' > payload.json
            - echo "$res_curatedocker_payload"
            - echo `read_json payload.json "image"`
            - cat payload.json | echo
            - docker pull `read_json payload.json "image"`

