resources:
  - name: curatemaven
    type: IncomingWebhook
    configuration:
      webhookName: curate_maven

  - name: mygitrepo
    type: GitRepo
    configuration:
      gitProvider: Github_Sample
      path: shimib/curation_pre
      branches:
        include: main

pipelines:
  - name: CurateMaven
    steps:
    - name: ExampleStep
      type: Bash
      configuration:
        integrations:
          - name: artifactory
        inputResources:
          - name: curatemaven
        runtime:
          type: image
          image:
           auto:
            language: java
            versions:
              - "17"
      execution:
          onExecute:
            - mvn -version
            - python --version
            - python3 --version
            - ls -laR
