resources:
  - name:       curatedocker
    type:       IncomingWebhook
    configuration:
      webhookName: curate_docker

pipelines:
  - name: CurateDocker
    steps:
    - name: ExampleStep
      type: Bash
      configuration:
        integrations:
          - name: artifactory
        inputResources:
          - name: curatedocker
      execution:
          onExecute:
            - echo ${int_artifactory_url} ${int_artifactory_user} 
            - docker login -u ${int_artifactory_user} -p ${int_aritfactory_apikey} `echo "${int_artifactory_url}" | sed -E 's/.*\/\/([^\/]+).*/\1/'`
            - echo "$res_curatedocker_payload" | jq '.' > payload.json
            - echo "$res_curatedocker_payload"
            - echo `read_json payload.json "image"`
            - cat payload.json | echo
            - docker pull `read_json payload.json "image"`

